### ISSUE TITLE
Segmentation Inference

### ISSUE THREAD

**Issue by zzl2022** [Gollini/NSCLC_Radiogenomics#2]
Hi, 
The script gave the following error when I try Lung tumor segmentation mask.

Traceback (most recent call last):
  File "G:\4.24_NSCLC_Radiogenomics-main\NSCLC_Radiogenomics-main\radiogenomics\main.py", line 52, in <module>
    main()
  File "G:\4.24_NSCLC_Radiogenomics-main\NSCLC_Radiogenomics-main\radiogenomics\main.py", line 44, in main
    inference = Inference(args.input, args.output, args.dataset)
  File "G:\4.24_NSCLC_Radiogenomics-main\NSCLC_Radiogenomics-main\radiogenomics\experiments\inf_seg.py", line 72, in __init__
    self.model.load_state_dict(torch.load(self.weights_path))
  File "D:\anaconda3\envs\py3.9\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda3\envs\py3.9\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

How can I successfully load weights?
Thanks!

**Comment by cszjq** [comment]
您好，请问您解决了吗？

**Comment by zzl2022** [comment]
> 您好，请问您解决了吗？

没有解决

**Comment by GTziolas** [comment]
This is still an issue. Author should upload weights somewhere or make them accessible to us.
